### ISSUE TITLE
Advanced search button location

### ISSUE THREAD

**Issue by pdelgado248** [NEUBIAS/bise#100]
I think it would be better to have an advanced search button below the search bar so that it can be accesed from any section (Forums, About BISE, How to curate...) the same way the simple search can be accesed now.

I suggest having it there instead of devoting a section only for advanced search.

**Comment by miura** [comment]
![image](https://user-images.githubusercontent.com/272781/67442943-0cb47a80-f603-11e9-8d9d-23519b219304.png)

Looks  OK!

**Comment by miura** [comment]
done
