### ISSUE TITLE
In advance search, when searching for top EDAM higher level concepts, lower level hits are not included

### ISSUE THREAD

**Issue by joakimlindblad** [NEUBIAS/bise#102]
Example: 

Advanced search for: Operation "Alignment construction"
http://biii.eu/all-content?type=All&field_has_function_target_id%5B%5D=4192&field_type_target_id=All

Result: 7 hits
Desired result: Inclusion (perhaps lower ranked) of all sub-operations

Advanced search for: Operation "Image registration" which is a subtopic of the former
http://biii.eu/all-content?type=All&field_has_function_target_id%5B%5D=4055&field_type_target_id=All

Results: 33 hits

**Comment by matuskalas** [comment]
The same when clicking on an EDAM concept in the tree.
