### ISSUE TITLE
Option for OR style advanced searches

### ISSUE THREAD

**Issue by joakimlindblad** [NEUBIAS/bise#103]
Interface for searching for e.g. Operation A or B
Current interface seems to only provide A and B, which usually leads to very few results

An option is to always provide OR results, but rank the hits such that AND ends up on top of the list.

**Comment by PerrineGilloteaux** [comment]
closed as duplicate (or at least related since it seems the exact contrary of what was requested :)) of https://github.com/NEUBIAS/bise/issues/112
