### ISSUE TITLE
Hits and pagination hell

### ISSUE THREAD

**Issue by matuskalas** [NEUBIAS/bise#106]
See e.g. https://biii.eu/cell-segmentation

- [ ] Show total number of hits

- [ ] Don't paginate after 10 items, PLEASE (also current bio.tools do but that's just as awful)

- [ ] Ideally don't paginate at all (infinite scroll or "load more" might be more modern), or if then in a usable way

- [ ] If paginating, show which of how many hits are shown (e.g. 51-100 of 234 items)

- [ ] If paginating, allow also on the top, w/o scrolling

- [ ] If one scroll down through the whole https://biii.eu/cell-segmentation, it looks in the right bottom corner like if there is only 1 page with hits

- [ ] If paginating and Drupal allows, number pages starting from 1, not from 0! https://biii.eu/cell-segmentation?page=1 is page 2!

- [ ] Show hits in a more compact way, without the lengthy scrolling and hard to see border between tools if scrolling fast. Use more width. See e.g. https://bio.tools/t (that's a bit the opposite extreme with the width perhaps)

**Comment by PerrineGilloteaux** [comment]
Closed and merged to https://github.com/NEUBIAS/bise/issues/107 
(taxonomy term view)
