### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by joakimlindblad** [NEUBIAS/bise#113]
Add to .htaccess Header set Access-Control-Allow-Origin "*"

**Comment by miura** [comment]
pull request #114

**Comment by miura** [comment]
requested changes are now in the test site - in the branch devaccess. As soon as the external access is successful, it will be merged into the dev.

**Comment by joakimlindblad** [comment]
This works well on both test.biii.eu and biii.eu; thus closing. Thanks Kota!

**Comment by miura** [comment]
Hi @joakimlindblad  
could you try changing the pointer to biii.eu instead of test.biii.eu? biii.eu should work. 
test.biii.eu is really being tested for upgrading to Drupal9 now. 
Cheers, 
Kota

**Comment by joakimlindblad** [comment]
We've been using biii.eu for a long time now, so that was not the reason. However, I see that the problem is no longer around. You or some other divine being seems to have fixed it :-) Thus closing again.
