### ISSUE TITLE
COMULIS website

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NEUBIAS/bise#126]
for now in comulis.eu/correlation-software-porto2019

**Comment by delestro** [comment]
After _bii.eu_ gives the NodeID in the json file, we need to change all the links in the comulis page from _test.bii.eu_ to _bii.eu_

**Comment by delestro** [comment]
@PerrineGilloteaux need to solve issue #115 https://github.com/NeuBIAS/bise/issues/115

**Comment by PerrineGilloteaux** [comment]
here is an example of the new view REST export using ontology ((Advanced Search like) :
http://test.biii.eu/all-content-rest?type=software&field_has_function_target_id%5B%5D=4192&field_type_target_id=All&_format=json

**Comment by PerrineGilloteaux** [comment]
https://docs.google.com/document/d/1uJYBo6KLU4j7tSad-kCXjnT2-zA1YwbEerUwDCFMzgI/edit?usp=sharing

**Comment by joakimlindblad** [comment]
After a very successful hackathon at taggathon 9, we reached far!

What remains is
1. To propagate fixes implemented on test.biii.eu to the main biii.eu
2. To change the link in the biii_search.js to point to biii.eu
3. To make it the main comulis.eu/correlation-software page

Did I forget anything?

@PerrineGilloteaux can you let us know when point 1 is done, so that @delestro can continue with steps 2 & 3.

Thank you both for great work!!

**Comment by PerrineGilloteaux** [comment]
@delestro @joakimlindblad Hi Joakim and Felipe, could you either share the code of the comulis webpage (so I can check all the field you need are here after the makeover that has been done?)  , or we can organize a specific virtual hackaton to this point and deploy it for good on the comulis website.

**Comment by joakimlindblad** [comment]
@PerrineGilloteaux 
The code is here: https://github.com/delestro/comulis
Afaics we use: nid, body, field_image, title   
I just found where the js is in the Site, and can update to move from test -> biii if that is suitable.

**Comment by joakimlindblad** [comment]
The "all-content-rest" interface seems gone from both main biii and test. The Comulis search uses that to filter out Multimodal things.

**Comment by joakimlindblad** [comment]
When using "searchjsonexport" I only get 10 entries. Is this an intensional limit? Can I get all somehow?
Also, I get some hits which do not contain much, with relevance 5 and 4.
I get the same hits also in the web interface: http://biii.eu/search?search_api_fulltext=visualization
See here attached image (after Paintera):
![image](https://user-images.githubusercontent.com/25959603/87257001-a2e14700-c497-11ea-9c0c-b9eab2cb18da.png)

**Comment by PerrineGilloteaux** [comment]
For  dev here is the code source of the COMULIS webpage -> https://github.com/delestro/comulis

**Comment by joakimlindblad** [comment]
**Seems to work again! :-)**
Thanks for all the help @miura and @PerrineGilloteaux !

Closing the issue. Documentation of update steps below.
(Note: The "empty hits" issue is still there, will open a separate lower prio github issue for that.)

```
For your information (when you need to do the similar in future), what I did was:

    with local test.biii(dev)
        import production database. (lando db-import)
        import configration from file to database. 
        drush cr, 
        change the setting in GUI as requested
        export configuration
        commit changes to dev, push to upstream dev
    pull from inside ovh test, import configuration. drush cr, check test.biii.eu

    locally, switch to the production branch, cherrypick only two relevant commits from dev
        drush config-import & cr to see if it is OK.  
        as it was working, push to upstream production. 
    pull from inside the ovh production, import configuration changes, drush cr

Cheers, 
Kota

```

**Comment by PerrineGilloteaux** [comment]
Hi:  the problem was indeed that the res output of both request that you areusing were returning only 10 outputs, thetwo dupal views has been updated to dislpay all items (only rest export views) . The corresponding commit is  334f76f044acf4789fa419ec5644beb4897c4b27
