### ISSUE TITLE
curation of content

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NEUBIAS/bise#136]
https://docs.google.com/spreadsheets/d/13mzalAjb_lUO7pxktC7pJfv5EtYzZVVchTvAXGMjMbY/edit#gid=0

**Comment by czhci** [comment]
observation:

in "author", there exists: 
first name last name, 
last name, first name 
the orcid id link

**Comment by czhci** [comment]
observation:

in "main" for entry name, there exist variations to identify software name, for example:
to indicate watershed that is in imagej, in these formats: 
watershe (imagej),
imagej watershed
watershed for imagej

should we normalize these?

**Comment by czhci** [comment]
there is a lack of deformable transformtion in adam topic. 
also under geometric transformation, it is not exhaustive, e.g. similarity transform is not there.
in general, there is some minor discrepancy in the hierarchy levels.

**Comment by czhci** [comment]
what should it be, for an entry that is a component in a software, but the content of this component is a tutorial? e.g. http://biii.eu/roi-tutorial-1

**Comment by czhci** [comment]
there is a lack of tags in the available "has topic" and "has function", when the entry is not exactly handling images, but general data/files.

**Comment by czhci** [comment]
version 1 of entries on biii.info (biii.upf.edu) done (edam alpha 0.4).

**Comment by czhci** [comment]
appended entries added between 2017 and 2018 (before ontology time) to be curated.

**Comment by PerrineGilloteaux** [comment]
Hi @czhci could you have a look to see if we can close this issue? Also because we have the tag-me page (now set such taht it shows the entries with no authors, but could be changed) , we may not need to have an issue open, but rather to mention the existence of this page ? and potentially change it so confirmed taggers can also search for example for entries with not biological terms)?

**Comment by czhci** [comment]
Agreed. Will also go over the whole list, since many have already been curated. And will update the list with only those need curation. Will go through the tag-me page as well.
