### ISSUE TITLE
NOTE THAT EDITION IS DONE IN TEST.BIII.EU FOR URGENT TEST…, done in local installation in parralel

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NEUBIAS/bise#138]
-> two problem -> can not import the biiii.datbase in the local branch from Alain -> so turn around is actually importing database from test.biii.eu rather than biii.eu -> IMPORTANT NOTICE HERE for deployment
-> COMULIS workgroup need immediate deployment to test.biii.eu for going on with the interfacing-> then the workflow for taggathon bordeaux for myself is as follow: I moduify the database on the test.bii.eu and do config export (bad I know) that I send to Alain for commit). Alain is working on his local version for file system edition, and we are sitting together

**Comment by PerrineGilloteaux** [comment]
here is the description of the error when importing biii prod content on ALain branch -> mport the listed configuration changes? (yes/no) [yes]:
 > yes

 [error]  Drupal\Core\Config\ConfigImporterException: There were errors validating the config synchronization.
Entities exist of type <em class="placeholder">Custom block</em> and <em class="placeholder">Custom block type</em> <em class="placeholder">Basic block</em>. These entities need to be deleted before importing. in Drupal\Core\Config\ConfigImporter->validate() (line 737 of /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php).

In ConfigImportCommands.php line 261:
                                                                                                                                                                             
  The import failed due to the following reasons:                                                                                                                            
  Entities exist of type <em class="placeholder">Custom block</em> and <em class="placeholder">Custom block type</em> <em class="placeholder">Basic block</em>. These entities need to be deleted before importing.
                                                                                                                                                                             

config:import [--preview [PREVIEW]] [--source SOURCE] [--partial] [--diff] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--druplicon] [--notify [NOTIFY]] [--xh-link XH-LINK] [--] <command> [<label>]

**Comment by miura** [comment]
- Importing / exchanging database to / with the new theme in _dev_ branch
- test.biii.eu is running with the latest database & theme

... so I guess this is done, so please reopen (especially @PerrineGilloteaux )
