### ISSUE TITLE
Advanced search JSON does not match JSON format of Full text search

### ISSUE THREAD

**Issue by joakimlindblad** [NeuBIAS/bise#139]
Full text search: http://test.biii.eu/searchjsonexport?search_api_fulltext=(?=visualization)&_format=json
gives a JSON of the format [{key1:value1,key2:value2,...

The advanced search: http://test.biii.eu/all-content-rest?type=software&field_has_function_target_id%5B%5D=4192&field_type_target_id=All&_format=json
gives a JSON of a different format [{key1:[{value1}],key2:[{value2}],...

This makes parsing complicated. 
Desired: The advanced search JSON format should be same as the Fulltext search JSON format

**Comment by PerrineGilloteaux** [comment]
I will do this, but apart the {} from the content it self of the field displayed in this view do you want the same exact list if fields? (it goes with another issue with was unformization of both Search results views).

**Comment by joakimlindblad** [comment]
For now no need for that. If needed I will file another issue on that.
This is **not** related to issue #115, that is an independent issue.

**Comment by PerrineGilloteaux** [comment]
title
field image link 
nid
Description

**Comment by joakimlindblad** [comment]
[Solved] Thank you!
