### ISSUE TITLE
fiji search give the rule of short link creation

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NEUBIAS/bise#143]

**Comment by PerrineGilloteaux** [comment]
Rules of renaming for links: http://biii.eu/admin/config/search/path/settings
1) a, an, as, at, before, but, by, for, from, is, in, into, like, of, off, on, onto, per, since, than, the, this, that, to, up, via, with WILL BE REMOVED (if separated words, not part of another word)
2) Maximum alias length 100. Maximum length of aliases to generate.
3) everything converted to lowercase
4) When a pattern includes certain characters (such as those with accents)  transliterate them into the US-ASCII alphabet. (%20)

RULES OF REPLACEMENT for PUNCTUATION: 
SEPARATOR  = -
ONLY SPACE and - are replace by separator -. All other signes not alphanumeric are removes (?#@ , ; )

**Comment by haesleinhuepf** [comment]
Hi @PerrineGilloteaux and @albangaignard ,

the BIII search is now integrated on a git branch. It looks like this:
![image](https://user-images.githubusercontent.com/12660498/75762047-598b2900-5d3a-11ea-831c-785bcf176d1d.png)

Please try it out in your Fiji by downloading the [scijava-search.jar](https://owncloud.mpi-cbg.de/index.php/s/IXnMbtlPpD7Er3Q) and putting it in the /jars/ sub-directory of your Fiji installation. Please also remove the other scijava-search.jar.

If everything works fine, I'll send a [pull-request for the changes](https://github.com/scijava/scijava-search/commit/7fa61e0cd04183d5dbc903139bf5ef0ca724415d) to the Scijava/Fiji maintainers.

Cheers,
Robert

**Comment by PerrineGilloteaux** [comment]
@haesleinhuepf looks ok: remond me wich Search you are using? Search api? if yes the good news is that in the new version of search, it will Search in tag so much more efficient than simple free text.

**Comment by PerrineGilloteaux** [comment]
Many thanks for this, sounds ok for release for me.

**Comment by haesleinhuepf** [comment]
Thanks for testing, I'll send the PR.

The search URL is this one btw:
https://github.com/scijava/scijava-search/commit/7fa61e0cd04183d5dbc903139bf5ef0ca724415d#diff-27e98126dd7dcf4dfdbac33f29e558d1R77

Cheers,
Robert
