### ISSUE TITLE
Kota cleaning the base version on dev with the prod database

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NEUBIAS/bise#146]
https://github.com/NEUBIAS/bise/tree/dev20191022newTheme
has been deployed  test.biii.eu. It will be deployed in its actual state on dev branch, then  if functional on prod, to start fresh again with a correct dev and prod branch.

**Comment by miura** [comment]
For issues listed by @czhci , they are mostly (?) made into individual issues and are handled independently. As major issues have been solved (except for the advanced search fixes and improvements), the new version is now deployed to the production server. ... so I close this thread.
