### ISSUE TITLE
issues withe the status of dev branch (test.biii.eu) as of 20200612

### ISSUE THREAD

**Issue by miura** [NEUBIAS/bise#148]
- "type" view components, collections ...) lists items but the link to pages are not present.

**Comment by PerrineGilloteaux** [comment]
-  pages created but not diaplyed in the menu (such as Show Taggers) http://test.biii.eu/show-taggers

**Comment by PerrineGilloteaux** [comment]
Copied in different issues so closing this one: one ticket per problem, the the label "dev branch"
