### ISSUE TITLE
Wiki: Lando start

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NeuBIAS/bise#15]
In Updating the Site (routine procedure!), the mention to lando start , (to launcg the app ) is missing.
Can you add it saying also that http://bisescratch.lndo.site/ should now be available in the navigator?

**Comment by miura** [comment]
@PerrineGilloteaux  OK I will add these steps to the wiki.

**Comment by miura** [comment]
https://github.com/NeuBIAS/bise/wiki/BISE-development/be1cb28c2f909b9812b7fa59259b2f879630c372
