### ISSUE TITLE
pages created but not diaplyed in the menu 

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NEUBIAS/bise#150]
(such as Show Taggers) http://test.biii.eu/show-taggers

**Comment by miura** [comment]
@PerrineGilloteaux  
I added "Taggers" to the main navigation

![image](https://user-images.githubusercontent.com/272781/84580648-06188480-add9-11ea-97e5-63ccd305b0f5.png)

What other pages should be in the main menu? I will add them.

**Comment by miura** [comment]
see https://github.com/NEUBIAS/bise/issues/151#issuecomment-643705099
