### ISSUE TITLE
on the homepage, below “Welcome to Biii”, the text “This block is broken or missing. You may be missing content or you might need to enable the original module.”

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NEUBIAS/bise#151]
should be gone or replaced by something? Gone I guess. Idem for the NEUBIAS block at the bottom of tha page.

**Comment by miura** [comment]
@PerrineGilloteaux  I can fix if you tell me what was there under "Welcome to Biii". If you think there was indeed nothing (it seems that this "broken" part is also within the "welcome to Biii" block), I will generate a similar block again and place it in the same position. 

![image](https://user-images.githubusercontent.com/272781/84581016-0ca8fb00-addd-11ea-9ddd-9d5821d2ff86.png)

**Comment by miura** [comment]
... having said that, maybe @alat54 still has the correct block. Menus, Custom blocks, and taxonomy terms are not exported by drush config:export, so the command based on the module "structured sync" should be used to export these configurations to files. https://www.drupal.org/project/structure_sync

**Comment by PerrineGilloteaux** [comment]
Hi @miura , this is indeed the case of a custom block, I and ALain have the original (archive from Bordeaux). For now and before tomorrow, to set back the prod alive, I would suggest to disabled (see commit below) , Alain has no time until next week.

**Comment by miura** [comment]
https://github.com/NEUBIAS/bise/commit/cf0444edb4ac9a8ef58c4724acebe7fca7e27998
