### ISSUE TITLE
Fixed back search API for comulis on dev version

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NEUBIAS/bise#152]
Test configuration on COMULIS not ok  https://www.comulis.eu/correlation-software-porto2019#search_result
(check configuration https://github.com/PerrineGilloteaux/BIII-BORDEAUX-changes-in-config
problem in search API, to be corrected to the config version above)

Same thing with FIJI test BAR

**Comment by miura** [comment]
Are these colients pointing to test.biii.eu or biii.eu?

**Comment by PerrineGilloteaux** [comment]
@delestro @joakimlindblad could you confirm where the search is done?

**Comment by PerrineGilloteaux** [comment]
IMPORTANT:1 )REBUILD TRACK INDEX, (admin/config/search/search-api/index/default_index = Rebuild tracking information at the bottom) 2)run reindexation (start indexing now after), same page,  3) and drush cr before seing effects did you do do so? I do not want to test it myself on test.biii.eu @miura

**Comment by miura** [comment]
done in test.biii.eu. Please confirm and then close! @PerrineGilloteaux

**Comment by joakimlindblad** [comment]
I don't find where @delestro inserted the js code, but according to his github, it's getting data from https://test.biii.eu

**Comment by miura** [comment]
I confirmed that it's working in the comulis site. I think the search in COMULIS website should point to biii.eu.
