### ISSUE TITLE
php version in lando

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NEUBIAS/bise#153]
https://github.com/NEUBIAS/bise/blob/dev/.lando.yml
it is now 7.1, while most of the drupal packages of this dev branch are said to require php >7.2, so lando composer install would not work with this lando.yml 
I suggest to change the version to 7.2 in lando.yml, do you see any problem with that? (then lando rebuild)

**Comment by miura** [comment]
done, this change will be there in the next push.
