### ISSUE TITLE
untracked missing file(social media)

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NEUBIAS/bise#158]
/modules/contrib/social_media/icons/google_plus.svg
to be taken and renamed from
https://upload.wikimedia.org/wikipedia/commons/5/5c/Google_plus.svg
(not tracked in git)

**Comment by miura** [comment]
In fact, they don't have one in the source repository...
https://git.drupalcode.org/project/social_media/-/tree/8.x-1.x/icons

**Comment by miura** [comment]
The developer of this module (social_media) removed the google plus link recently 

https://www.drupal.org/project/social_media/issues/3113361

but this is effective only when installing, so I removed it in the setting. 

https://github.com/NEUBIAS/bise/commit/bf01f86a5a2feaf0dfddcf184bc4653c69963c56
