### ISSUE TITLE
question updating edam in production?

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NeuBIAS/bise#16]
- solution 1: do it directly on the data base (after testing locally) from Florian's Script.
- solution 2: taxonomy terms are content (module structured sync)
tested by Kota? procedure complex
Which one should be preferered

**Comment by miura** [comment]
I tested the **solution 2**, and think that the procedure is complex as data flows through multiple layers: 

Webprotege / bio.tool > Github / sturctured_sync text files > inject into database via drush commands > import to taxonomy via drush commands. 

**Solution 1** is more straightforward (if my understanding is correct - please check @florian-levet ):  

Webprotege / bio.tool > text file >  inject to database in production site via sql commands. 

For the simplicity, I think **Solution 1 should be taken**.
