### ISSUE TITLE
display the total NUMBER of entries for every list of certain type

### ISSUE THREAD

**Issue by czhci** [NEUBIAS/bise#161]
it would be nice for EXISTING biii pages that give a list of a certain type the total number of entries in the list, like these: http://test.biii.eu/taxonomy/term/3575, http://test.biii.eu/taxonomy/term/3574, etc. Especially when they are accessed through the all content listing table (http://test.biii.eu/all-content).

**Comment by PerrineGilloteaux** [comment]
done for http://test.biii.eu/all-content

Not done for taxonomy terms , but result can be obtained when entering the term in advanced search .
