### ISSUE TITLE
Search API indexing fails in parsing some texts

### ISSUE THREAD

**Issue by miura** [NEUBIAS/bise#169]
While indexing for search API, there are many warnings such as

`>  [warning] An overlong word (more than 50 characters) was encountered while indexing: sampledriftcorrectionfollowing4dconfocaltimelapseimaging.<br />Since database search servers currently cannot index words of more than 50 characters, the word was truncated for indexing. If this should not be a single word, please make sure the "Tokenizer" processor is enabled and configured correctly for index Default content index.`

It seems that HTML paths are also indexed and causing such index keys that are very long and unusable.

**Comment by miura** [comment]
The Stopwords processor should come after the Tokenizer. WIth this processing order, there is no failure in parsing URL paths. 

![image](https://user-images.githubusercontent.com/272781/85573071-d9b10380-b635-11ea-9171-170eeec6e4bb.png)

I will push this soon.

**Comment by PerrineGilloteaux** [comment]
Great thanks . 
Kota , Chong suggestion is a good one but what do you mean by we can not add content anymore ? Why can we put this version live and let people now adding things now that is is correctly merge with this data base ?

**Comment by miura** [comment]
deployed.
