### ISSUE TITLE
defining List of test before accepting pulling

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NeuBIAS/bise#17]
minimal list of test to be performed before accepting pulling to master:
site refer to local installation :
test 1  site/soft should return a json formatted list of software
To be continued...

**Comment by vcaldas** [comment]
I guess we should have only few people allowed to push to Master.
Master = Production, so it has to be running smooth on the pc before.

Maybe we have to implement a series of automated test routines, but I neved done that...

**Comment by miura** [comment]
Hi @vcaldas , current test run by Travis is off-the-shelf tool for Drupal but it might be OK with this. For low-level problems such as php coding and so on is captured by this test. 

We need to decide who are the admins. 

By the way, I directly pushed recaptcha addition & activation yesterday, as there was a storm of registration by bots from servers in U.S, in the last minute it was like every 10 minutes. As an Emergency measure, I pushed the changes directly to `master`... but then think that for admins, it should be OK to directly push to `dev` at any time. What do you think? (also @PerrineGilloteaux )

**Comment by vcaldas** [comment]
Is this part of the tutorials? We might close this issue and open new ones with more clear tasks. @PerrineGilloteaux @miura

**Comment by miura** [comment]
yes, this is rather a general issue. let's close.
