### ISSUE TITLE
Editing entries: Error message

### ISSUE THREAD

**Issue by haesleinhuepf** [NEUBIAS/bise#170]
Hi all,

I just tried to edit an entry in BIII and I'm getting an error message:
![image](https://user-images.githubusercontent.com/12660498/85699839-2222fc80-b6dc-11ea-82df-64544b7649c8.png)

However, I can't see the field which is wrongly filled. This is the entry I tried to change:
http://biii.eu/node/1430/edit?destination=/node/1430

Let me know if I can help further tracing this down!

Awesome work btw. everyone!

Cheers,
Robert

**Comment by miura** [comment]
Hi Robert, I cannot reproduce on my desktop ... would you tell me your OS and the browser?

![image](https://user-images.githubusercontent.com/272781/85711793-ec841080-b6e7-11ea-91e3-8d86b898da61.png)

**Comment by haesleinhuepf** [comment]
Sure. Windows 10 and Chrome. The error popped up after updating some links btw.

**Comment by miura** [comment]
Thanks, OK, I will try to do some similar editing actions and see what will happen. I tried editing a link in an entry using MacOS - Chrome but it did not happen...

**Comment by miura** [comment]
Hi @haesleinhuepf  
Do you still experience the same?
