### ISSUE TITLE
"software" on "Advanced search" page points to wrong page

### ISSUE THREAD

**Issue by czhci** [NEUBIAS/bise#173]
on the “Advanced search” page, in the second column of listing content table, Category, when clicking “Software”, it returns this [page](http://biii.eu/admin/structure/types/manage/software), which should be this page (http://biii.eu/software) instead.

**Comment by miura** [comment]
@czhci  please check tes.biii.eu - It's fixed now and waiting for deployment. 

![image](https://user-images.githubusercontent.com/272781/86516747-8738c980-be23-11ea-8fd0-c155f9c17f83.png)

**Comment by czhci** [comment]
test site is okay. I guess the deployment on productino site would do! thanks, Kota!

**Comment by miura** [comment]
deployed.
