### ISSUE TITLE
The appearance of workflow steps

### ISSUE THREAD

**Issue by miura** [NEUBIAS/bise#174]
"workflow steps" better 

1. Appear in the sidebar or so, because there is a huge spacing above the download link and people probably cannot find those links (see below). 
2. It needs to be limited with its appearance only in workflows, not in components and collections. (#82 )

![image](https://user-images.githubusercontent.com/272781/86310307-0361c000-bc1e-11ea-9960-edfdec3526ac.png)

**Comment by miura** [comment]
I will test try adding this module "conditional fields":

https://www.drupal.org/project/conditional_fields

https://www.drupal.org/docs/8/api/form-api/conditional-form-fields

For views, maybe this as well for the rendered page. 
https://www.drupal.org/project/views_conditional

**Comment by miura** [comment]
.. For point number 1, unnecessary "workflow field" display can be simply deleted by editing the entry in the general interface (somehow, in this "3D ImageJ Suite case", workflow step field was added with empty values).  Whenever there is such empty space, it might be due to the old version "workflow steps". 

...For point number 2, I will describe the solutin in #82

**Comment by miura** [comment]
Here are two cases, software type "collection" (workflow steps field becomes hidden), and type "workflow". @PerrineGilloteaux , @czhci , Please check these updates in test.biii.eu, by testing, to add new software content. 

**case "Collection"**
![image](https://user-images.githubusercontent.com/272781/86516830-2067e000-be24-11ea-9ac3-9c8e07208ea3.png)
![image](https://user-images.githubusercontent.com/272781/86516836-2958b180-be24-11ea-91b9-e6b3c3121871.png)

**case "workflow"**
![image](https://user-images.githubusercontent.com/272781/86516841-3c6b8180-be24-11ea-9552-eeedf9264bd6.png)
![image](https://user-images.githubusercontent.com/272781/86516845-42616280-be24-11ea-864e-df20f5e8e0eb.png)

**Comment by czhci** [comment]
seems okay on test.biii.eu. Let's check after deployment on prod.

**Comment by miura** [comment]
deployed.
