### ISSUE TITLE
BIII json export problem

### ISSUE THREAD

**Issue by hmenager** [NEUBIAS/bise#175]
I have a problem with biii.eu: the json list of softs happens to be badly formatted lately, providing for each tool an HTML link instead of the software name (http://biii.eu/soft?_format=json). Now an entry looks like that:

```
{"title":"\u003Ca href=\u0022\/node\/1642\u0022 hreflang=\u0022en\u0022\u003End-safir\u003C\/a\u003E","nid":"1642"}
```

@albangaignard also mentions that the test server has the same issue.

**Comment by PerrineGilloteaux** [comment]
is fixed by https://github.com/NEUBIAS/bise/commit/72e2823ad00d3ca7d81d49fba2b32d7a57a32d0b , pull request to come, checking for any other rest export issues

**Comment by miura** [comment]
Looks OK.  
Perrine, please avoid closing the issue until it becomes online, at least in the test site. 

![image](https://user-images.githubusercontent.com/272781/86952471-56be9b80-c153-11ea-89dc-8e231ace957c.png)

**Comment by miura** [comment]
I will pull from the test.biii.eu soon.

**Comment by miura** [comment]
It's now in test.biii.eu. 
@hmenager  Please test replacing the pointer to test.biii.eu temporally.

**Comment by hmenager** [comment]
Looks good to me on the test server. Thank you @PerrineGilloteaux @miura  !

**Comment by PerrineGilloteaux** [comment]
> Looks OK.
> Perrine, please avoid closing the issue until it becomes online, at least in the test site.

Hello Kota, many thanks for this , I think did not close it, but when you refer an issue in a commit with words such as "fix", accepting a pull request containing this commit will close the relative issue , I will then try to avoid the list of keywords mentionned here that makes this process automatic
https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by joakimlindblad** [comment]
Works. Fix deployed. Closing
