### ISSUE TITLE
Make Page title <title> reflect the name "BioImage Informatics Index"

### ISSUE THREAD

**Issue by joakimlindblad** [NEUBIAS/bise#179]
Transition from BISE -> BIII

Current title is: <title>Bioimage Informatics Search Engine (BISE) | BIII</title>
Desired title: <title>BioImage Informatics Index (BIII)</title> (or similar)

Also, Name should be stated early in https://biii.eu/about  , possibly with a comment on the transition from the BISE name.

**Comment by PerrineGilloteaux** [comment]
Hi @joakimlindblad : "Name should be stated early in https://biii.eu/about , possibly with a comment on the transition from the BISE name."-> Fully agree 

But where do you see the title? I could not find BISE somewhere on biii.eu or test.biii.eu?  You mean in github ?

**Comment by PerrineGilloteaux** [comment]
for first point the content of the page are git hub not tracked per se, they are inside the content database , as all other entries.

**Comment by joakimlindblad** [comment]
<title> of the webpage, see screenshot
![image](https://user-images.githubusercontent.com/25959603/131992760-ff39a484-9f47-49f9-8c32-4cb4c84fa6d2.png)

**Comment by joakimlindblad** [comment]
So, if it is content of the database, where to file an issue about that? :-) And, more importantly, how to get it changed :-)

**Comment by miura** [comment]
Hi @joakimlindblad @PerrineGilloteaux 

I changed the home page title so it's now there on biii.eu. Please check. 
This cannot be changed as a file (or maybe, through structure sync) so it will be like normal contents, only in the database. \

**Comment by joakimlindblad** [comment]
Yes! Works as it should :-)

Thanks @miura Kota!

/ Joakim
