### ISSUE TITLE
Change headline to "Advanced search" on the Advanced search page

### ISSUE THREAD

**Issue by haesleinhuepf** [NEUBIAS/bise#196]
Can we change the headline to `Advanced search` on the Advanced search page?

![image](https://user-images.githubusercontent.com/12660498/235289150-41bcc423-81e9-4c9c-b0cc-53ee505f182b.png)

**Comment by PerrineGilloteaux** [comment]
Corrected in  https://github.com/NEUBIAS/bise/commit/ac378416e350f69dba3e9ab54da330c071bddb9f , to be deployed

**Comment by miura** [comment]
done. 
b4884e0a1460e4f76b68461a66b85a62009f05eb
