### ISSUE TITLE
Multiple identical rows in the tag-me page

### ISSUE THREAD

**Issue by czhci** [NEUBIAS/bise#211]
Many entries appear repeatedly, see below an example:

<img width="1107" alt="Screenshot 2023-05-17 at 16 32 55" src="https://github.com/NEUBIAS/bise/assets/3789738/e5684626-043e-4edf-b590-f353005163a3">

**Comment by miura** [comment]
This is fixed in the dev branch now. 
https://test.biii.eu/tag-me-

![image](https://github.com/NEUBIAS/bise/assets/272781/bf09bfb3-46fa-4333-800a-1f209211bf0e)

will be deployed. 
https://github.com/NEUBIAS/bise/commit/bb08c29d1ca0e59cd4a476b1dd88d2f0436c5d6b
