### ISSUE TITLE
Find a new theme to replace Zircon

### ISSUE THREAD

**Issue by miura** [NeuBIAS/bise#25]
Theme "Zircon" is not supported anymore. As our theme is based on Zircon, we need to replace it with another theme. 

![zirconterminated](https://user-images.githubusercontent.com/272781/40920367-9edbe3b6-680c-11e8-9aba-b44ef5bf112a.png)

For more details, see [the web page of zircon](https://www.drupal.org/project/zircon). 

Quote:

This module is unsupported due to a security issue the maintainer didn’t fix. See Zircon - Critical - Unsupported - SA-CONTRIB-2018-037 for details.
If you want to use this module, your options are:

- Choose another, actively maintained module instead
- File an issue in the queue with a patch to fix the module and then contact the security team to have your version reviewed and the project handed over to you following the unsupported project process.
- Hire someone to fix the security bug so the module can be re-published and supported (Consider hiring companies listed in the Marketplace)

**Comment by miura** [comment]
One candidate is [Bootstrap theme](https://www.drupal.org/project/bootstrap), which is bridging the [Bootstrap Framework](http://getbootstrap.com/) and Drupal. This is the base theme, and there are several themes based on this with ready-to-go style setups. For example, see this page: 

  [Top 10 free bootstrap based Drupal themes](https://www.vardot.com/en/blog/top-10-free-bootstrap-based-themes-drupal-8-0)

**Comment by vcaldas** [comment]
I like the "Tweme" and also the "showcase_lite"

**Comment by PerrineGilloteaux** [comment]
Apparently the zircon has been solved and has found a new maintainer and the problem was actually for D7 (and erroneously reported for D8) https://www.drupal.org/project/zircon/issues/2976313

**Comment by PerrineGilloteaux** [comment]
I m updated on dev the drupal core version and other security issue and will check if the warning is still here

**Comment by vcaldas** [comment]
@PerrineGilloteaux Any uptade in this issue?

**Comment by miura** [comment]
https://github.com/NeuBIAS/bise/issues/47#issuecomment-460067519

**Comment by PerrineGilloteaux** [comment]
a new theme is been tested together with Felipe Delestro, it is on development on the branch newmockup.

**Comment by miura** [comment]
The warning for the Zircon version is now gone. I think it's fixed, but let's keep the Bootstrap theme in `newmockup` as a candidate for the renewal (a new issue).  I close this isse for now.
