### ISSUE TITLE
CRON Error Could not delete temporary file 

### ISSUE THREAD

**Issue by miura** [NeuBIAS/bise#45]
The following error appears for every CRON run. 

```
Could not delete temporary file "temporary://neubiaslogo_Beq_icon.ico" during garbage collection
```

Need to work with sql-cli to get rid of this. 

https://www.drupal.org/project/drupal/issues/2802803

>As others have mentioned if you're just trying to clean out a handful of entries, they exist in the file_managed table. You can do so with phpmyadmin or if you don't have that installed you can do 'drush sql-cli' to get into an sql command interface, and then remove the offending entry with something like
>
>   `delete from file_managed where filename = "LaKelly.jpg";`
>
>edit:
>
>or if you want to clear all listings that pertain to a certain folder (which in my case was long gone), you'd do
>   `delete from file_managed WHERE uri LIKE '%wp-content%';`

>back up your database before trying the above. Looks like in my case although the logs only showed the first 100 or so error messages, Drupal was trying to delete 3700 files that no longer existed.

**Comment by PerrineGilloteaux** [comment]
@miura any news for it?

**Comment by miura** [comment]
Now fixed with the following command (for the production database)

`drush sql:query "delete from file_managed where filename = 'neubiaslogo_Beq_icon.ico'"`
