### ISSUE TITLE
bise wiki development

### ISSUE THREAD

**Issue by miura** [NEUBIAS/bise#46]
@vcaldas  

I updated the development wiki page

https://github.com/NeuBIAS/bise/wiki/BISE-development#development-custom-theme-bise

I separated it into three big sections

- installation procedure
- how to develop
- actual development examples

This is just to notify - and there still are many typos but please ignore those at the moment. By the way, internal linking does not work - is there a good way to anchor sections?

**Comment by vcaldas** [comment]
Cool! I'll take a look and check on the links. I remember being possible.

**Comment by miura** [comment]
Internal link in the wiki working, so I close this issue.
