### ISSUE TITLE
Add comment broken 

### ISSUE THREAD

**Issue by czhci** [NeuBIAS/bise#69]
The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Drupal\Core\Entity\EntityStorageException</em>: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;377-0-0-en&#039; for key &#039;PRIMARY&#039;: INSERT INTO {comment__comment_body} (entity_id, revision_id, bundle, delta, langcode, comment_body_value, comment_body_format) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6); Array
(
    [:db_insert_placeholder_0] =&gt; 377
    [:db_insert_placeholder_1] =&gt; 377
    [:db_insert_placeholder_2] =&gt; comment
    [:db_insert_placeholder_3] =&gt; 0
    [:db_insert_placeholder_4] =&gt; en
    [:db_insert_placeholder_5] =&gt; &lt;p&gt;test&lt;/p&gt;

    [:db_insert_placeholder_6] =&gt; basic_html
)
 in <em class="placeholder">Drupal\Core\Entity\Sql\SqlContentEntityStorage-&gt;save()</em> (line <em class="placeholder">783</em> of <em class="placeholder">core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php</em>). <pre class="backtrace">Drupal\Core\Database\Statement-&gt;execute(Array, Array) (Line: 625)
Drupal\Core\Database\Connection-&gt;query(&#039;INSERT INTO {comment__comment_body} (entity_id, revision_id, bundle, delta, langcode, comment_body_value, comment_body_format) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6)&#039;, Array, Array) (Line: 358)
Drupal\Core\Database\Driver\mysql\Connection-&gt;query(&#039;INSERT INTO {comment__comment_body} (entity_id, revision_id, bundle, delta, langcode, comment_body_value, comment_body_format) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6)&#039;, Array, Array) (Line: 32)
Drupal\Core\Database\Driver\mysql\Insert-&gt;execute() (Line: 1304)
Drupal\Core\Entity\Sql\SqlContentEntityStorage-&gt;saveToDedicatedTables(Object, , Array) (Line: 886)
Drupal\Core\Entity\Sql\SqlContentEntityStorage-&gt;doSaveFieldItems(Object) (Line: 578)
Drupal\Core\Entity\ContentEntityStorageBase-&gt;doSave(NULL, Object) (Line: 429)
Drupal\Core\Entity\EntityStorageBase-&gt;save(Object) (Line: 774)
Drupal\Core\Entity\Sql\SqlContentEntityStorage-&gt;save(Object) (Line: 390)
Drupal\Core\Entity\Entity-&gt;save() (Line: 376)
Drupal\comment\CommentForm-&gt;save(Array, Object)
call_user_func_array(Array, Array) (Line: 111)
Drupal\Core\Form\FormSubmitter-&gt;executeSubmitHandlers(Array, Object) (Line: 51)
Drupal\Core\Form\FormSubmitter-&gt;doSubmitForm(Array, Object) (Line: 589)
Drupal\Core\Form\FormBuilder-&gt;processForm(&#039;comment_comment_form&#039;, Array, Object) (Line: 318)
Drupal\Core\Form\FormBuilder-&gt;buildForm(&#039;comment_comment_form&#039;, Object) (Line: 48)
Drupal\Core\Entity\EntityFormBuilder-&gt;getForm(Object) (Line: 249)
Drupal\comment\Controller\CommentController-&gt;getReplyForm(Object, Object, &#039;field_give_feedback_on_this_soft&#039;, NULL)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber-&gt;Drupal\Core\EventSubscriber\{closure}() (Line: 582)
Drupal\Core\Render\Renderer-&gt;executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber-&gt;wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber-&gt;Drupal\Core\EventSubscriber\{closure}() (Line: 151)
Symfony\Component\HttpKernel\HttpKernel-&gt;handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel-&gt;handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle-&gt;handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache-&gt;pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache-&gt;handle(Object, 1, 1) (Line: 50)
Drupal\ban\BanMiddleware-&gt;handle(Object, 1, 1) (Line: 59)
Drupal\httpbl\HttpblMiddleware-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware-&gt;handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware-&gt;handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel-&gt;handle(Object, 1, 1) (Line: 693)
Drupal\Core\DrupalKernel-&gt;handle(Object) (Line: 19)
</pre>

**Comment by PerrineGilloteaux** [comment]
Hi, I ve posted the question here, I am surprised that we are the only ones with this bug…
([https://www.drupal.org/forum/support/post-installation/2019-02-06/fix-an-integrity-violation-with-comments-in-drupal-867](https://www.drupal.org/forum/support/post-installation/2019-02-06/fix-an-integrity-violation-with-comments-in-drupal-867))

**Comment by PerrineGilloteaux** [comment]
Updating Drupal core to 8.6.10 AND rebuilding the permissions (admin/reports/status/rebuild) corrected the bug for me locally.
