### ISSUE TITLE
Bug in expanding the taxonomy

### ISSUE THREAD

**Issue by matuskalas** [NEUBIAS/bise#70]
Now with EDAM alpha04 in BIII/BISE:

+ Operation
   -> Alignment construction
                   Here it should continue expanding further to Image registration
                   The taxonomy exists correctly in BIII/BISE
                   But it cannot be expanded in BIII/BISE

**Comment by PerrineGilloteaux** [comment]
actually this is a kniown bug in Drupal 8.6.x https://www.drupal.org/project/drupal/issues/2997960

**Comment by PerrineGilloteaux** [comment]
The limitation happen for term with MULTIPLE PArents: for example image registration had also the image processing parent. (where you can find it then) http://biii.eu/image-registration.
So it is a limited bug but still a bug. The new taxonomy menu module may solved it, but the 3.4 version was buggy soi let's wait a little bit..

**Comment by miura** [comment]
Shall we anyway update taxonomy menu @PerrineGilloteaux ? The dev version is pretty fresh. 

>Development version: 8.x-3.x-dev updated 5 Feb 2019 at 17:13 UTC

**Comment by PerrineGilloteaux** [comment]
taxonomy is not anymore expandable in the website it self
