### ISSUE TITLE
Switch to EDAM alpha05 - Needed curation afterwards

### ISSUE THREAD

**Issue by matuskalas** [NEUBIAS/bise#72]
There have been 1 concept that changed from Operation to Topic in EDAM alpha05, and changed ID!:
- [ ] Neuron image analysis. Update entries by adding it as hasTopic in BISE/BIII:
        - Paintera, Rivulet 2, Aivia, CEM, VMTK: Vascular Modeling Toolkit, Neurite Tracer, Simple Tracing DF-Tracing, nctuTW, Reconstruct, JFilament

And 2 removed:
- [ ] Interactive segmentation. Replace by Interaction level attribute in BISE/BIII:
        - PartSeg, The Allen Cell Structure Segmenter, Interactive watershed, Orbit, FlyLimbTracker, SuRVoS, QuimP, QuPath, FibrilTool, ilastik - Carving

- [ ] Local thresholding. Consider other concept underneath & including Image segmentation:
        - clij - GPU-acceleration for ImageJ

Related: #44, https://github.com/edamontology/edam-bioimaging/issues/14

Note for long term:
(not part of this issue or relevant today, but keep in mind when designing sustainable updating)
In Bio.Tools it turned out that it's needed to keep the annotations with old versions of EDAM, too. Of course marked as obsolete, but not removed once EDAM is updated. This hasn't been done and users are unhappy about it.

**Comment by matuskalas** [comment]
And notes for the ongoing alpha06_dev developments:
(No action in BISE/BIII needed soon!)

Concept that changed wrong ID from EDAM alpha01-alpha05:
- Region of interest

Concept to double-check (WebProtégé bug|feature):
- Multimodal imaging

Removed:
- none yet

**Comment by PerrineGilloteaux** [comment]
Hi @florian-levet 
any updates on the update?

**Comment by florian-levet** [comment]
Hi,
After modification of the script, it seems to work. I will do a couple of tests today and tomorrow and will update you. But it should be ok this week.
