### ISSUE TITLE
BISE search in ImageJ/Fiji

### ISSUE THREAD

**Issue by haesleinhuepf** [NeuBIAS/bise#74]
Dear *,

I'm following up a discussion during the NEUBIAS conference. There is a search plugin for Fijis search bar, which allows searching in the BISE online database:
https://github.com/scijava/scijava-search/blob/master/src/main/java/org/scijava/search/web/BISESearcher.java

It is at the moment deactivated because of an issue in the website (its HTML is no valid XML) because of a missing slash. Read details here:
https://forum.image.sc/t/search-field-on-menu/6958/7

What do you think about reviving this search plugin? I'd be happy to help, but I need support by a developer on server side to put this slash there...

Cheers,
Robert

**Comment by PerrineGilloteaux** [comment]
waiting deployment
