### ISSUE TITLE
Common error with Lando/composer and corrections

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NeuBIAS/bise#75]
- Message such as /app/xx not found with lando . 
Solution: restart docker and lando
- Message such as Connection to SQL database impossible (with lando drush cr for example) -> Solution: check your .env and your settings.local.: credential to your local database may not be correct .

**Comment by miura** [comment]
This is due to the miss-configured .lando.yml, or missing of the file itself. See https://github.com/NeuBIAS/bise/pull/71#issuecomment-466382476
