### ISSUE TITLE
Workflow entries behaviour and suggestions

### ISSUE THREAD

**Issue by Leandroscholz** [NEUBIAS/bise#77]
Dear team, 
@PerrineGilloteaux  @miura @czhci, 

I added about 9 new workflows and a bunch of components/collections on bise this week (used in BIAFLOWS) and I noticed a few issues and undesired behavior when adding them. 
1) ``previous workflow step`` autocompletes to existing biii.eu nodes, but it should (I assume) trace back to existing steps in the workflow being described. 
2) ``current workflow step`` if read that way (considering what I just wrote in 1) ) should be renamed as current workflow component/process and this indeed must autocomplete to an existing biii.eu node, which should Ideally link to a component.
3) Step numbers. Shouldn't this be set automatically as they are added/reordered? I would say the template using "Step number: description" should be changed just to "description" and we then should use an automatic step number (I am not sure how feasible this is, so definitely open to discussion). 

I can give as an example a workflow that has a simple overview of what it does and does not have steps associated to a certain biii.eu (I consider this acceptable but not ideal)  below. it should show how 1) affects the way we add the workflows and why I think this should be fixed. 

![image](https://user-images.githubusercontent.com/29718327/53510566-98025e00-3abe-11e9-8e4e-95b8629d8e3d.png)

in this example, I could not associate the step order since they are not associated with biii.eu nodes. but I would add the workflow as steps 12 and 34 running in parallel, then 5 getting results of 2 and 4 to run. 

Please let me know if additional clarification is needed. I hope these comments help. 

Cheers, 
Leandro.

**Comment by PerrineGilloteaux** [comment]
Hi Leandro sorry the version is not updated yet on prod...

**Comment by Leandroscholz** [comment]
@PerrineGilloteaux  oh, ok then. Sorry! How is that working on dev? Maybe I should set things up in my pc to check it. 

cheers,
Leandro.

**Comment by miura** [comment]
Hi @Leandroscholz 

http://test.biii.eu/ 

is now in the latest status. Please check if your issues are still the issue...

Kota

**Comment by miura** [comment]
Just now looking at how this "workflow steps" is working. 

My opinion is that there does not have to step numbers - treat it as just a list of components, roughly in the sequence of appearance. 

The major reason is that the majority of workflows are not a single path. Multiple paths applied to different channel images and sometimes even some feedback loop. For knowing the outline of the workflow, it's much easier to see the script. 

From my point of view, it's better to be called "Used Components" instead of "workflow steps".

**Comment by miura** [comment]
@PerrineGilloteaux @czhci please check if these three points (see suggestions by @Leandroscholz at the top of this thread)!

**Comment by PerrineGilloteaux** [comment]
not perfecttly (step number not automatically). But workflow visualisation needs to be seen as a first version, in order to push forward idscussions. I'm then closing it.
