### ISSUE TITLE
Tagger page error

### ISSUE THREAD

**Issue by miura** [NeuBIAS/bise#81]
Taggers page is causing some error:

http://biii.eu/taggers?page=0&sort_by=name&sort_order=ASC

![image](https://user-images.githubusercontent.com/272781/53974265-89412a00-4102-11e9-91c0-002572cde5d3.png)

![image](https://user-images.githubusercontent.com/272781/53974479-f228a200-4102-11e9-9f35-f439123cc627.png)

**Comment by miura** [comment]
It seems that the problem happens because "Family name" and the "User name' are both "Name". I will try to fix this.

**Comment by PerrineGilloteaux** [comment]
The view biii.eu/taggers is not used anymore, it has been replaced by http://biii.eu/show-taggers.
