### ISSUE TITLE
Permission rights to be changed for anonymous

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NEUBIAS/bise#85]
Some fields are not visible to anaonymous (not logged in) users: for example requires, programming language. I do not think it make sense.

**Comment by miura** [comment]
I just now tried unlogged (the anonymous mode in Chrome) and looks OK:

![image](https://user-images.githubusercontent.com/272781/54843282-51c2a800-4cd4-11e9-8b68-eb7d2186fb28.png)

What is the environment that you accessed biii? Maybe dependent on the browser.

**Comment by miura** [comment]
I would say this is fixed. Please reopen if you still find the same issue appearing. @PerrineGilloteaux
